import mongoose from 'mongoose';

const ticketSchema = new mongoose.Schema({
    // Id is autogenerated by Mongo
    code: {
        type: String,
        unique: true,
        required: true
        // Logic to autogenerate this unique code will be in the Service/DAO
    },
    purchase_datetime: {
        type: Date,
        default: Date.now // Defaults to the exact creation time
    },
    amount: {
        type: Number,
        required: true
    },
    purchaser: {
        type: String, // Will contain the user's email
        required: true
    }
});

const TicketModel = mongoose.model('Ticket', ticketSchema);
export default TicketModel;